lab50:
  files:
    - !exclude "*"
    - !exclude countdown.c
    - !include fibo.c
    - !include garbage.c
    - !include initializations.c
    - !include mean.c
    - !include minesweeper.c
    - !include pokemon.c
